name: Book
on: [push]

jobs:
  build:
    name: Run
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v1
      - name: Run
        uses: DevExpress/testcafe-action@latest
        env: # Or as an environment variable
          LOGIN_USERNAME: ${{ secrets.USER_NAME }}
          LOGIN_PASSWORD: ${{ secrets.PASSWORD }}
        with:
          args: "chrome index.js"